version: 0.2

env:
  # parameter-store:
  #   TOOLING_ACCOUNT_ID: /op/$STAGE/AWS_ACCOUNT_ID
  #   AWS_ACCOUNT_ID: /op/$STAGE/AWS_ACCOUNT_ID
  secrets-manager:
    TOKEN_SLACK: $AWS_SECRET_ARN:TOKEN_SLACK
    API_SLACK: $AWS_SECRET_ARN:API_SLACK
    CHANNEL_SLACK: $AWS_SECRET_ARN:CHANNEL_SLACK
phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      # - npm install -g yarn
      - sudo apt-get install zip -y
      # Install njsscan
      - pip3 install njsscan --quiet
      - echo "Installed njsscan"
      - npm install --package-lock
  build:
    commands:
      # - yarn install --production=false
      # - npx prisma generate
      # - yarn build
      - npm install nth-check@latest
      #Run nodejs-scan
      - mkdir -p report
      - njsscan . --html --output report/njsscan-report.html
      - export PATH_TO_REPORT=report/njsscan-report.html
      - export TYPE_REPORT=njsscan
      - echo "Reactjs-scan completed"
      #Run OWASP Dependency Check
      - bash dependency-check/bin/dependency-check.sh --project "OWASP Dependency Check" --scan $(pwd)/src --format "ALL" --nvdApiKey "66a986ca-b5fd-4aab-bb0b-c9e5f10edf7c" --out $(pwd)/report
      - echo "OWASP Dependency Check completed"
      # Run linter
      # - yarn lint
  post_build:
    commands:
      - bash binsast/build-notify.sh $API_SLACK $TOKEN_SLACK $CHANNEL_SLACK $REPO $PATH_TO_REPORT $TYPE_REPORT

artifacts:
  files:
    - $(pwd)/report/dependency-check-report.html
    - $(pwd)/report/dependency-check-junit.xml
cache:
  paths:
    - '$(pwd)/node_modules/**/*'

