version: 0.2

# env:
#   secrets-manager:
#     NODE_ENV: $AWS_SECRET_ARN:NODE_ENV
#     SONAR_URL: $AWS_SECRET_ARN:SONAR_URL
#     SONAR_TOKEN: $AWS_SECRET_ARN:SONAR_TOKEN
#     SONAR_PROJECT_KEY: $AWS_SECRET_ARN:SONAR_PROJECT_API_KEY_PURAVIDA
phases:
  # install:
  #   # runtime-versions:
  #   #   nodejs: 18
  #   commands:
  #     # Copy odc reports
  #     - echo $CODEBUILD_SRC_DIR_sastout_api_service
  #     - |
  #       if ! [ -z ${CODEBUILD_SRC_DIR_sastout_api_service+x} ] ; then
  #         cp -R $CODEBUILD_SRC_DIR_sastout_api_service/odc-reports $CODEBUILD_SRC_DIR
  #       fi
  build:
    commands:
      # - cd $CODEBUILD_SRC_DIR
      - docker login --username nghialmgcd201527 --password Minhnghia@123
      - |
        docker run \
        --rm \
        -e SONAR_HOST_URL="http://ec2-18-136-210-171.ap-southeast-1.compute.amazonaws.com:9000" \
        -e SONAR_SCANNER_OPTS="-Dsonar.projectKey=final-project -Dsonar.sources=." \
        -e SONAR_TOKEN=sqp_10dc69d7130ad2db06895a64563bd45c395c2fa8 \
        -v "$(pwd):/usr/src" \
        sonarsource/sonar-scanner-cli
      - echo "build stage completed"
      - echo "Test again"
      - echo "Test"
      - echo "Test"
