version: 0.2
phases: 
  install:
    commands:
      - echo "Installing dependencies..."
      - npm install
  build:
    commands:
      - echo "Building the React project..."
      - npm run build
  post_build:
    commands:
      - echo "Uploading files to S3 bucket..."
      - aws s3 sync build/ s3://final-project-facial-recognition-app --delete
