#!/bin/sh

set -e

RED='\033[0;31m'
GREEN='\033[0;32m'
NO_COLOR='\033[0m'

HELP="${RED}Command not found: detect-secrets
${NO_COLOR}To install the command line tool: ${GREEN}https://github.com/Yelp/detect-secrets#installation
${NO_COLOR}To learn more about this tool: ${GREEN}https://github.com/Yelp/detect-secrets#usage
${NO_COLOR}You can bypass this hook using --no-verify option. ${RED}USE AT YOUR OWN RISK!${NO_COLOR}"

if which detect-secrets > /dev/null; test $? != 0; then
  echo -e "${HELP}"
  exit 1
else
  echo -e "${NO_COLOR}Checking secrets..."
  git diff --staged --name-only -z | xargs -0 detect-secrets-hook --baseline .secrets.baseline
  echo -e "${GREEN}No secrets detected!${NO_COLOR}"
fi